server:
  port: 5555

spring:
  application:
    name: zuulservice
  profile:
    active: default
  cloud:
    config:
      url: http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: info, health, mappings, env, refresh, routes

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
