server:
  port: 8081

spring:
  application:
    name: organizationservice
  profiles:
    active: default
  cloud:
    config:
      enabled: true
    stream:
      bindings:
        output:
          destination: orgChangeTopic
          content-type: application/json
      kafka:
          binder:
            zkNodes: 182.61.133.92:2181
            brokers: 114.67.66.81:9092
  zipkin:
    baseUrl: http://localhost:9411

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/user