tracer:
  property: "this is default"

redis:
  port: 6379

spring:
  jpa:
    database: "mysql"
    show-sql: "true"
    properties:
      hibernate:
        hbm2ddl:
          auto: "update"
  datasource:
    platform: "mysql"
    driverClassName: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://114.67.66.81:3306/shop"
    username: "root"
    password: "{cipher}4aee9542ab85cf039814fd611d4887316b4216f1a1d6c66d1f004dabe14d7944"
    testWhileIdle: "true"
    validatingQuery: "select 1"

example:
  property: demo-property